services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: mini-database-api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATA_DIR=/code/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s