FROM python:3.11-slim

WORKDIR /code

RUN apt-get update && apt-get install -y \
    gcc \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . ./app

EXPOSE 8000

ENV PYTHONUNBUFFERED=1
ENV DATA_DIR=/code/app/data

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]